###
# About/contact for the site author
#
# name of the author of the site
name = "Programming Club IITM"
# description to display in the sidebar
description = "<span class=\"codinfox-changing-keywords\"><b class=\"visible\">Where coding becomes an art.</b><b class=\"hidden\">Where algorithms are masterpieces.</b></span>"

# the profile image of the author to display in the sidebar
gravatar = "955199a8639b75e98f6efd05e71727da" # md5 hash of your email address # sidebar.html

# contact links to reach the author
#  - `name` is the font-awesome char name
#  - `path` is the link to follow 
contact = [
  { name = "linkedin", path = "https://www.linkedin.com/company/programming-club-cfi-iit-madras/" },
  { name = "github", path = "https://github.com/programmingclubiitm" },
  # { name = "facebook", path = "https://" },
  # { name = "twitter", path = "https://twitter.com/svavs" },
  { name = "instagram", path = "https://instagram.com/programmingclub_iitm/" },
  # { name = "lastfm", path = "https://www.last.fm/user/svavsa" },
  # { name = "tumblr", path = "http://svavs.tumblr.com/" },
  { name = "email", path = "mailto:programmingclubiitm@gmail.com" },
  { name = "youtube", path = "https://www.youtube.com/@programmingclub_iitm" },
]
